### ISSUE TITLE
Log in fails, and reports missing translation

### ISSUE THREAD

**Issue by jasonivers** [doorkeeper-gem/doorkeeper#1307]
### Steps to reproduce
Update to 5.2 from 5.1

The more detailed the issue, the more likely that we will fix it ASAP.

Don't use GitHub issues for questions like "How can I do that?" —
use [StackOverflow](https://stackoverflow.com/questions/tagged/doorkeeper)
instead with the corresponding tag.

### Expected behavior
I should log in successfully

### Actual behavior
Updating to the most recent version this morning caused an error with a missing translation, and then failed to login, and had an error message that had #{value}, presumably meaning it was used as a string literal rather than being interpreted.

The missing translation was doorkeeper.errors.messages.invalid_request.missing_param

Rolling back to 5.1 fixed the problem

### System configuration
You can help us to understand your problem if you will share some very
useful information about your project environment (don't forget to
remove any confidential data if it exists).

**Doorkeeper initializer**:

**Ruby version**:
2.6.3

**Gemfile.lock**:

**Comment by nbulaj** [comment]
Hi @jasonivers . Thanks for reporting the issue. It's related to #1306

Could you please try to use master branch of this repo and check if it works?

**Comment by nbulaj** [comment]
Released as 5.2.1, let me know if it fixed the issue!

**Comment by mjankowski** [comment]
I had this same issue, and updating to 5.2.1 does fix that specific error.

Sort of related -- will there be an upgrading instructions section update for 5.2.x in the wiki? Is it now required to explicitly set `default_scopes` in the config (or otherwise interact with scopes in a way that wasn't previously required?). Despite that locales issue being fixed I'm still getting some other errors, and am not sure yet if it's something I need to change in my specs, or a doorkeeper config I need to change.

**Comment by nbulaj** [comment]
Yep, @mjankowski , I need to check all the PRs and collect changes to write migration guide. I'll try to do it ASAP, but don't sure how fast it would be :(

**Comment by beaorn** [comment]
So just to confirm, is it actually required now in >= 5.2 to set default_scopes in the initializer?

Enforcing a public scope after not having one forces to to have all of your oauth2 clients to re-authorize to have permission for the scope after setting one.

**Comment by jasonivers** [comment]
Apparently it is fixed when both updating and adding default_scopes.

**Comment by ansonhoyt** [comment]
I'm still getting the missing translation error when `default_scopes` isn't configured.

```
ActionView::Template::Error: missing translation: doorkeeper.errors.messages.invalid_request.missing_param
```

 I wouldn't expect `default_scopes` to be required since it defaults to `:public` per the [Scopes](https://doorkeeper.gitbook.io/guides/configuration/scopes#access-token-scopes) guide and [Using Scopes](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes).

I just upgraded now that https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/85 was merged and released.

**Comment by ansonhoyt** [comment]
My mistake, I found that the [install_generator.rb](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/install_generator.rb#L16) copies `en.yml` to my project. So I re-ran `rails g doorkeeper:install` and got the missing translation. 🎉 

I'll keep an eye out for @nbulaj to land the migration guide in case I miss anything else.
