### ISSUE TITLE
Allow grant_type: password without client_id and client_secret on non-confidential clients

### ISSUE THREAD

**Issue by netgusto** [doorkeeper-gem/doorkeeper#382]
Is it possible to implement password credentials flow (as described here https://github.com/applicake/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow) but without requiring to send the client_id and client_secret credentials to the token endpoint ?

OAuth2 RFC does not enforce the presence of `client_id` nor `client_secret` for `grant_type: password` on non-confidential clients (like @EmberJS applications) http://tools.ietf.org/html/rfc6749#section-4.3

**Comment by Morpheu5** [comment]
I'm still getting this

    ActiveRecord::StatementInvalid (SQLite3::ConstraintException: NOT NULL constraint failed: oauth_access_tokens.application_id: INSERT INTO "oauth_access_tokens" ("resource_owner_id", "token", "expires_in", "created_at", "scopes") VALUES (?, ?, ?, ?, ?))

on Doorkeeper 4.0.0.rc4. I'm not sure dropping the NOT NULL constraint post-hoc is a viable solution.

**Comment by tute** [comment]
> I'm not sure dropping the NOT NULL constraint post-hoc is a viable solution. It shouldn't be there in the first place, because it's clearly not necessary in all cases.

Hi! It makes sense that you drop it afterwards. It was indeed a bug that it existed in this form in previous versinos.

**Comment by Morpheu5** [comment]
Hi @tute! Yes, I'm just saying that I'm still running into this bug on a fresh install of 4.0.0.rc4.

**Comment by tute** [comment]
Indeed, I introduced this bug in: https://github.com/doorkeeper-gem/doorkeeper/pull/767/files. Want to send a PR to remove that FK constraint? Thanks for your report!

**Comment by Morpheu5** [comment]
No need for a PR, it was fixed in 6048f2ec0d80da097398b8d90a05aad278a80527 which is the next commit after 4.0.0.rc4, so I guess I'll have to wait for the next release, and remove the constraint manually in the meanwhile :)

**Comment by tute** [comment]
Thanks!

**Comment by voltechs** [comment]
We're still experiencing an issue where when `client_id` and `client_secret` are passed with empty values, it returns an exception of `Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`

For example, Postman will send them along even when they're empty. Is there anything in the OAuth Spec about ignoring empty strings?

**Comment by errawn** [comment]
> We're still experiencing an issue where when `client_id` and `client_secret` are passed with empty values, it returns an exception of `Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`
> 
> For example, Postman will send them along even when they're empty. Is there anything in the OAuth Spec about ignoring empty strings?

same here.

**Comment by SamaFoad** [comment]
I was getting exception 
"exception": "#<ActiveRecord::NotNullViolation: Mysql2::Error: Field 'application_id' doesn't have a default value>",
I have just removed the not null and it worked fine.
Hope this can help anyone
